# database config
DATABASE_NAME = "DATABASE_NAME"
DATABASE_USERNAME = "DATABASE_USERNAME"
DATABASE_PASSWORD = "DATABASE_PASSWORD"

PARAMETER_DATABASE_ENDPOINT = "DATABASE_ENDPOINT"
SECRETS_MANAGER_DB_CREDENTIAL = "DATABASE_CREDENTIAL"

# endpoints
ALLERGY_DETECTION_FEEDBACK = "/allergy_detection_feedback"
PREDICT_ALLERGY = "/predict_allergy"
ALLERGY = "/allergy"
