# database config
DATABASE_NAME = "DATABASE_NAME"
DATABASE_USERNAME = "DATABASE_USERNAME"
DATABASE_PASSWORD = "DATABASE_PASSWORD"

PARAMETER_DATABASE_ENDPOINT = "DATABASE_ENDPOINT"
SECRETS_MANAGER_DB_CREDENTIAL = "DATABASE_CREDENTIAL"

# endpoints
NEW_CHAT="/new-chat"
RECIPE_SUGGESSTION="/recipe-suggestions"